config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :goals
  get '/users/:id', to: 'users#show', as: 'user'
  root  'static_pages#home' 
  resources :tasks
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  has_many :tasks, :dependent => :destroy
  belongs_to :user
  validates :name, presence: true, length: { minimum: 4, maximum: 30 }
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
  has_many :goals
  validates :name, presence: true, length: { minimum: 4, maximum: 16 }

  def self.today_tasks
  	where(date: Date.yesterday.in_time_zone)
  end

  def self.tomorrow_tasks
  	where(date: Date.tomorrow.in_time_zone)  
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :new_goal
  require 'date'

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def new_goal
  	@new_goal = Goal.new
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def show
  	@goal_id = params[:id]
  	@task = Task.new
  	@user = current_user
  	@goal = @user.goals.find(@goal_id)
  	@tasks = @user.tasks.where(date: Date.today, goal_id: @goal_id)
  	@tomorrow_tasks = @user.tasks.where(date: Date.today+1)  
  	@goals = @user.goals 	

    #to do: clean this up!
    @user_tasks_goal = @user.tasks.select("date(date) as day, count(id) as tasks").where("goal_id = ?", @goal_id).group("date(date)")
    @complete_tasks = current_user.tasks.group("date(date)").where("complete = ? AND goal_id = ?", true, @goal_id).count
 
    @cmon = {}

    @user_tasks_goal.each {|d| @complete_tasks[d.day] = @complete_tasks[d.day].to_f/d.tasks}
    @complete_tasks.each {|k,v| @cmon[k.to_time.to_i] = v}
    
  	@cmon = @cmon.to_json
  end 

  def create 
  	@goal = current_user.goals.build(goal_create_params)
    @goal.color = current_user.goals.count + 1
    if @goal.save
      redirect_to @goal
    else
      redirect_to user_path(current_user.id)
    end
  end

  def destroy
    @goal= current_user.goals.find(params[:id])
    @goal.destroy
    respond_to do |format|
        format.html {redirect_to user_path(current_user.id)}
        format.js { render :action => "delete.js.erb" }
    end 
  end
  
  private

  def goal_create_params
    params.require(:goal).permit(:name)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
	super
  end

  def update
	super
  end

  private 
  def sign_up_params
    params.require(:user).permit(:name, :email, :password)
  end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if user_signed_in?
  	  redirect_to user_path(current_user.id)
  	end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save      
      respond_to do |format|
        format.html {redirect_to user_path(current_user.id)}
        format.js { render :action => "add_task.js.erb" }
      end 
    else
      render 'new'
    end
  end

  def update
    @task = current_user.tasks.find(params[:id])
    if params[:status] == 'change'
      @task.complete = !(@task.complete)
      if @task.save      
        respond_to do |format|
          format.html {redirect_to user_path(current_user.id)}
          format.js { render :action => "complete.js.erb" }
        end 
      end
    else
      @task.name = params[:task][:name]
      if @task.save      
        respond_to do |format|
          format.html {redirect_to user_path(current_user.id)}
          format.js { render :action => "edit.js.erb" }
        end 
      end
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy
    respond_to do |format|
        format.html {redirect_to user_path(current_user.id)}
        format.js { render :action => "delete.js.erb" }
    end 
  end

  private

  def task_params
    params.require(:task).permit(:name, :date, :complete, :goal_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@task = Task.new
  	@user = current_user
  	@tasks = @user.tasks.where(date: Date.today)
  	@tomorrow_tasks = @user.tasks.where(date: Date.today+1)  
  	@goals = @user.goals


    @user_tasks_goal = @user.tasks.select("date(date) as day, count(id) as tasks").group("date(date)")
    @complete_tasks = @user.tasks.group("date(date)").where("complete = ?", true).count
 
    @cmon = {}

    @user_tasks_goal.each {|d| @complete_tasks[d.day] = @complete_tasks[d.day].to_f/d.tasks}
    @complete_tasks.each {|key,value| @cmon[key.to_time.to_i] = value}
    
  	@cmon = @cmon.to_json
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_add_goal.html.erb
<!-- Modal -->
<div class="modal fade" id="newGoal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a goal:</h4>
      </div>
    
    <div class="modal-body">  
      <%= form_for @new_goal do |f| %>
        <%= f.label :name %> 
        <%= f.text_field :name, class: 'form-control' %> 
      <div class="actions">
    <%= f.submit "Create", class: "btn btn-sm btn-success" %>
      </div>
    <% end %>
    </div>     
    </div>
  </div>
</div>

app/views/goals/_goal.html.erb
<div class="goal-menu-container">
  <span class="glyphicon glyphicon-stop color-<%=goal.color%>"></span> 
  <li class="goals">
    <%=link_to goal.name, goal_path(goal.id) %>
  </li>
</div> 

app/views/goals/delete.html.erb
<%= link_to goal_path(task.id), method: :delete, :remote => true  do %>
  <span class="glyphicon glyphicon-trash delete" aria-hidden="true"></span>
<% end %>

app/views/goals/show.html.erb
<div class="container righty"> 
  <div class="row"> 

  
    <div class="col-xs-4">
      <span class="glyphicon glyphicon-stop color-<%=@goal.color%>"></span> <h1 class="goal-name"> <%= @goal.name %> </h1>
    </div>
    <div class="col-xs-5">      
      <%= link_to goal_path(@goal.id), method: :delete, data: {confirm: "Delete this goal?"}   do %>
        <span class="glyphicon glyphicon-trash delete goal-menu-icon" aria-hidden="true"></span>
      <% end %>
    </div>
  </div>

 <div id="cal-heatmap"></div>
  <br>
  <br>
  <br>
  <section class ="today-tasks">
    <div class="row"> 
      <div class="col-md-2">
        <p class="header-to-do">Today to do: </p>
      </div>
	    <div class="col-md-6">      
        <div id ='today-list'>      
          <%= render @tasks %> 
        </div><hr>
        <div class='add-today'><%= render 'tasks/add_task_form' %></div>
        <div class='add-task-button'>Add task</div>
	    </div>
    </div>
  </section>

   
  <%= content_tag :div, class: "heatmap-data", data: {cmon: @cmon} do %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goall</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
<nav class="user-col">
  <ul class="main-menu">
    <li><%=link_to current_user.name, user_path(current_user.id) %> </li>
  
    <hr> 

    <div id="goal-list">
      <li>
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      Goals 
      </li>
      <li>
        <ul class="sub-menu">
          <%= render @goals %>
          <br>
          <li class="add-goal" data-toggle="modal" data-target="#newGoal"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>  Add goal
          </li> 
        </ul>
      </li>
    </div>
    <hr>
    
    <li><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
    <%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>    
  </ul>
</nav>

 <% end %>


<%= yield %>

<!--Modal for adding new goal in sub menu -->
<%= render 'goals/add_goal' %>

</body>
</html>

app/views/static_pages/home.html.erb
<div class="container-home">  
  <div class="content">
    <center> <h1>Reach your goals</h1>
    <p>Create daily tasks and track your goals.</p></center>
     <p> <%= current_user %></p>
     <% if current_user %>
       <%= link_to "Account", user_path(current_user.id) %>
     <% end %>
    <%= render "devise/registrations/new" %><br>
    <%= render "devise/sessions/new" %>
  </div>
</div>

app/views/tasks/_add_task_form.html.erb
<%= form_for(@task, remote: true)  do |f| %>
  <%= f.text_field :name, class: 'add-task-field' %> 
  <%= f.hidden_field :date, :value => Date.today %>
  <%= f.hidden_field :goal_id, :value => @goal_id %>
  <br>
  <%= f.submit "Create task", class: "btn btn-success btn-sm" %><span class="cancel">cancel</span>
<% end %>

app/views/tasks/_task.html.erb
<div id="task-container-<%=task.id%>">

  <% if task.complete %>
    <%= link_to task_path(id: task.id, status: 'change'), {:method => :patch, :remote => true} do %>
      <span class="glyphicon-check check-box glyphicon" aria-hidden="true"></span>
    <% end %>
  <% else %>
    <%= link_to task_path(id: task.id, status: 'change'), {:method => :patch, :remote => true} do %>
      <span class="glyphicon-unchecked check-box glyphicon" aria-hidden="true"></span>
    <% end %>
  <% end %>

  <div class="entire-task">

    <div class="edit-task-form">
      <%= form_for(task, remote: true)  do |f| %>
          <%= f.text_field :name, class: 'edit-task-field' %> 
        <%= f.hidden_field :date, :value => Date.today %> 
        <br>
        <%= f.submit "Update", class: "btn btn-success btn-sm" %><span class="edit-cancel">cancel</span>
      <% end %>
    </div>

    <div class="all-list-data">    
      <% if task.complete == true %>
        <li class = 'to-do complete'>
      <% else %>
        <li class = 'to-do'>
      <% end %> <%= task.name %></li>   

      <section class="icons">
        <span class="glyphicon glyphicon-pencil pencil" aria-hidden="true"></span>
        <%= link_to task_path(task.id), method: :delete, :remote => true  do %>
          <span class="glyphicon glyphicon-trash delete" aria-hidden="true"></span>
        <% end %>
      </section>
    </div>
  </div>
</div>

app/views/tasks/_task_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :Day %>
  <%= f.date_field :date, class: 'form-control' %> 
  <%= f.label :Name %>
  <%= f.text_field :name, class: 'form-control' %><br>
  <%= f.submit "Create task", class: "btn btn-success btn-block" %>
<% end %>

app/views/tasks/_tasks.html.erb
<% @today_tasks.each do |t| %>
  <div id="task-<%=t.id%>">
    <% if t.complete == true %>
      <li class = 'to-do complete'>
    <% else %>
      <li class = 'to-do'>
    <% end %> <%= t.name %></li>   

    
    <section class="icons">
      <%= link_to edit_task_path(t.id), :remote => true  do %>
        <span class="glyphicon glyphicon-check check-box" aria-hidden="true"></span>
      <% end %>

      <%= link_to edit_task_path(t.id), :remote => true  do %>
        <span class="glyphicon glyphicon-pencil pencil" aria-hidden="true"></span>
      <% end %>

      <%= link_to task_path(t.id), method: :delete, :remote => true  do %>
        <span class="glyphicon glyphicon-trash delete" aria-hidden="true"></span>
      <% end %>
    </section>

  </div>
<% end %>

app/views/tasks/add_task.js.erb
var task = '<%= j render @task%>';
$('#today-list').append(task);
$('.add-task-field').val('');
$('.add-today').hide()
$('.add-task-button').show()

//TO DO: make code below DRY (it's repeated in coffeescript)
$('.entire-task').hoverIntent(function() {
  
  var item = $(this);

  $(this).find('.pencil').click(function() {
    item.find('.edit-task-form').show();
    var selectedTask = item.find('.to-do').text();
    item.find('.edit-task-field').val(selectedTask.trim());
    item.find('.all-list-data').hide();
    item.find('.edit-task-field').focus();
  });

  $(this).find('.edit-cancel').click(function() {
    item.find('.edit-task-form').hide();
    item.find('.all-list-data').show();
  });

  $(this).find('.icons').show(300);
}, function() {
  $(this).find('.icons').hide(300);
});
 

app/views/tasks/complete.js.erb
var taskId = <%= @task.id %>;
$('#task-container-' + taskId).find('.to-do').toggleClass('complete');
$('#task-container-' + taskId).find('.check-box').toggleClass('glyphicon-check glyphicon-unchecked');

app/views/tasks/delete.js.erb
var taskId = <%= @task.id %>;
$('#task-container-' + taskId).find('.to-do').fadeToggle();
$('#task-container-' + taskId).find('.glyphicon').fadeToggle();

 

app/views/tasks/edit.js.erb
var currentElement = $('#task-container-' + <%= @task.id %>);
currentElement.find('.to-do').html("<%= @task.name %>");
currentElement.find('.edit-task-form').hide();
currentElement.find('.all-list-data').toggle();

 

app/views/tasks/new.html.erb
<div class="container righty"> 
  <div class="row">
    <div class="col-md-6">
      <%= render 'task_form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container righty"> 
  <h1 class="goal-name"> 
  <span class="glyphicon glyphicon-stop blue"></span> Your summary 
  </h1><br>
  <div id="cal-heatmap"></div>  
  <br>
  <br>
  <br>
  <section class ="today-tasks">
    <div class="row"> 
      <div class="col-md-2">
        <p class="header-to-do">Today to do: </p>
      </div>
	    <div class="col-md-6">      
        <div id ='today-list'>      
          <%= render @tasks %> 
        </div>
	    </div>
    </div>
  </section>

   <%= content_tag :div, class: "heatmap-data", data: {cmon: @cmon} do %>
  <% end %>
</div>